### ISSUE TITLE
Forked repository for faster improvements

### ISSUE THREAD

**Issue by anjmao** [yuyang041060120/ng2-validation#122]
Hi @yuyang041060120 You made great library for validators, but it still lacks some features and as I see Pull requests are not merged fast enough. I forked library to https://github.com/ng-validators/ng-validators and pushed npm package `@ng-validators/ng-validators`

Improvements I'm planning to make in forked repo.
1) Allow to pass AbstractControl to validator which will allow to easer compare min max values if they depend on other form controls.
2) Add travis build with test coverage.
3) Add core contributors to organisation to merge pull requests faster.
4) Add demo page for each validator https://ng-validators.github.io/ng-validators#/required

**Comment by jedsmith13** [comment]
@anjmao I notice both of those links are broken. Did your forked library not work out?

I noticed you have a forked version at [https://github.com/anjmao/ng-validators](https://github.com/anjmao/ng-validators) is this the work you have done on the project.

It would be nice to find someone maintaining a fork of this so that we can use its features without starting yet another for of this repo.

**Comment by intellix** [comment]
There's also: https://github.com/rsaenen/ngx-custom-validators
